<div class="row">
    <strong>List</strong>
  <p>List Id: <?= $listRef->getListId(); ?></p>
  <p>List Name: <?= $listRef->getListName(); ?></p>
  <p>List Type Name: <?= $listRef->getType()->getTypeName(); ?></p>
  <br />
    <strong><?= $listRef->getType()->getEntityName(); ?></strong>
  <ul>
  <?php foreach($this->members as $member) { ?>
      <li><?= $member->getName(); ?></li>
  <?php } ?>
  </ul>
</div>
