<div class="row">
    <strong>List</strong>
  <p>List Name: <?= $list->getList()->getListName(); ?></p>
  <p>List Type Name: <?= $list->getList()->getType()->getTypeName(); ?></p>
  <p>List Member Entity: <?= $list->getList()->getType()->getEntityName(); ?></p>
  <p>Member Id: <?= $list->getMemberId(); ?></p>
  <br />
    <strong>Materials</strong>
  <p>Material Collection Name: <?= $this->member->getMaterialCollectionName(); ?></p>
  <ul>
  <?php foreach($this->member->getMaterials() as $material) { ?>
      <li><?= $material->getMaterialName(); ?></li>
  <?php } ?>
  </ul>
</div>
