<div class="row">
    <strong>List</strong>
  <p>List Id: <?= $listRef->getList()->getListId(); ?></p>
  <p>List Name: <?= $listRef->getList()->getListName(); ?></p>
  <p>List Type Name: <?= $listRef->getList()->getType()->getTypeName(); ?></p>
  <p>List Member Entity: <?= $listRef->getList()->getType()->getEntityName(); ?></p>
  <br />
    <strong>Materials</strong>
  <ul>
  <?php foreach($this->members as $material) { ?>
      <li><?= $material->getMaterialName(); ?></li>
  <?php } ?>
  </ul>
</div>
