<div class="row">
    <ul>
        <li>
            <a href="<?php echo $this->url('user', array('action'=>'index'));?>">Users</a>
        </li>
        <li>
            <a href="<?php echo $this->url('list', array('action'=>'index'));?>">Lists</a>
        </li>
        <li>
            <a href="<?php echo $this->url('migration', array('action'=>'index'));?>">Migration</a>
        </li>
    </ul>
</div>
