<div class="row">
    <h3>Migrating Collections</h3>
    <p> converting</p>
</div>
<script language="JavaScript">
    $.ajax({
        url: "<?= $this->url('migration', array('action' => $this->migact)); ?>",
        type: 'GET',
        dataType: 'text',
        success: function(data) {
            console.log(data);
            $('#output').val(data);
        }
    });
</script>
<textarea id="output" cols="70" rows="30">
</textarea>
