<div class="row">
    <h3>Migration Controller</h3>
    <p><em>(these items must be done in order)</em></p>
    <ol>
        <li><a href="/migration/materials">Migrate Joomla colors to Material Items</a></li>
        <li><a href="/migration/collections">Migrate Joomla materials to Material Collection Lists</a></li>
        <li><a href="/migration/colorrefs">Create material references in collection lists and generate All Collections list</a></li>
    </ol>
</div>
