<div class="row">
    <h3>Migrating Materials</h3>
    <p> converting
        <span id="loading"><img src="/img/ajax-loader.gif"</span>
    </p>
</div>
<script language="JavaScript">
    $.ajax({
        url: "<?= $this->url('migration', array('action' => $this->migact)); ?>",
        type: 'GET',
        dataType: 'text',
        success: function(data) {
            console.log(data);
            $('#output').val(data);
            $('#loading').val('');
        }
    });
</script>
<textarea id="output" cols="70" rows="10">
</textarea>

<p>Next Step:<br />
  <a href="/migration/collections">Migrate Joomla materials to Material Collection Lists</a>
</p>


