Addresses:
    type: entity
    table: Addresses
    indexes:
        IDX_ED3BF7B5A76ED395:
            columns:
                - user_id
    id:
        addressId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: address_id
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 64
            fixed: false
        firstName:
            type: string
            nullable: false
            length: 32
            fixed: false
            column: first_name
        middleName:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: middle_name
        lastName:
            type: string
            nullable: false
            length: 32
            fixed: false
            column: last_name
        address1:
            type: string
            nullable: false
            length: 128
            fixed: false
        address2:
            type: string
            nullable: true
            length: 128
            fixed: false
        city:
            type: string
            nullable: false
            length: 64
            fixed: false
        state:
            type: string
            nullable: true
            length: 64
            fixed: false
        country:
            type: string
            nullable: false
            length: 64
            fixed: false
        zip:
            type: string
            nullable: false
            length: 16
            fixed: false
        phone:
            type: string
            nullable: false
            length: 32
            fixed: false
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: user_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
