Users:
    type: entity
    table: Users
    id:
        userId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: user_id
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 64
            fixed: false
        firstName:
            type: string
            nullable: false
            length: 32
            fixed: false
            column: first_name
        middleName:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: middle_name
        lastName:
            type: string
            nullable: false
            length: 32
            fixed: false
            column: last_name
        phone:
            type: string
            nullable: false
            length: 32
            fixed: false
    lifecycleCallbacks: {  }
